#!/usr/bin/env bash
# neofetch command
neofetch --disable kernel packages shell theme term icons resolution wm_theme --ascii --colors 06 01 01 05 01 06 04 --ascii_colors 06 --ascii_distro manjaro
# Source global definitions
if [ -f /etc/bashrc ];
then . /etc/bashrc
fi
# Enable bash programmable completion features in interactive shells
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi
alias cl="clear"
# Expand the history size
export HISTFILESIZE=10000
export HISTSIZE=500
export HISTCONTROL=erasedups:ignoredups:ignorespace
# Set default editor and pager program
export EDITOR=nano
export PAGER=less
# To have colors for ls
alias ls="ls --color=auto"
export CLICOLOR=1
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:*.xml=00;31:'
# Color for manpages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Setup a red prompt for root and a green one for users.
normal="\[\e[0m\]"
red="\[\e[1;31m\]"
blue="\[\e[1;33m\]"
if [ $EUID != 0 ] ; then
  #PS1="$normal[${blue}$(echo $MACHTYPE)$normal]"
  #PS1+="\n"
  PS1="$normal[$red$(date +'%-I':%M:%P)$normal]-\w>\$ $normal"
else
  #PS1="$normal[${red}$(echo $MACHTYPE)$normal]"
  #PS1+="\n"
  PS1="$normal[$red$(date +'%-I':%M:%P)$normal]-\$ $normal"
fi

for script in /etc/profile.d/*.sh ; do
        if [ -r $script ] ; then
                . $script
        fi
done

# end of file
