#!/bin/sh
# Maintainer: mischief chris <mischiefchristophe@gmail.com>

package=file
subpackage=
depends=""
description="Utility for determining the type of a given file or files"
source="ftp://ftp.astron.com/pub/file/file-5.39.tar.gz"

file() {
	cd file-5.39

	./configure \
		--prefix=/usr \
		--enable-fsect-man5 \
                --enable-static \
                --disable-libseccomp
	make
	make DESTDIR=$INSTALL_DIR install
}
